# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playfair_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 386)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setGeometry(QtCore.QRect(190, 90, 61, 16))
        self.lbl_key.setObjectName("lbl_key")
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(250, 90, 291, 31))
        self.txt_key.setObjectName("txt_key")
        self.lbl_input_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_input_2.setGeometry(QtCore.QRect(190, 150, 47, 13))
        self.lbl_input_2.setObjectName("lbl_input_2")
        self.txt_input = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_input.setGeometry(QtCore.QRect(250, 150, 291, 41))
        self.txt_input.setObjectName("txt_input")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(280, 210, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(410, 210, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.lbl_output = QtWidgets.QLabel(self.centralwidget)
        self.lbl_output.setGeometry(QtCore.QRect(190, 250, 47, 13))
        self.lbl_output.setObjectName("lbl_output")
        self.txt_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_output.setGeometry(QtCore.QRect(250, 250, 291, 41))
        self.txt_output.setObjectName("txt_output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_key.setText(_translate("MainWindow", "Nhap khoa:"))
        self.lbl_input_2.setText(_translate("MainWindow", "Plain text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Ma hoa"))
        self.btn_decrypt.setText(_translate("MainWindow", "Giai ma"))
        self.lbl_output.setText(_translate("MainWindow", "Ket qua:"))
        self.label.setText(_translate("MainWindow", "PLAYFAIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
